# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: AureumApes
          template: classic 
          base: header, activity, community, repositories
          config_timezone: Europe/Berlin
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: programming
          plugin_languages_colors: typewriter
          plugin_languages_limit: 15
          plugin_languages_recent_categories: programming
          plugin_languages_recent_days: 3
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
